---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age13hlaygu79nwrl75zazp9dan7pp0ypx4shyx5f8d7cwaa67xfhgdq04y6r6
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age13hlaygu79nwrl75zazp9dan7pp0ypx4shyx5f8d7cwaa67xfhgdq04y6r6
