# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CKgu81bDTTy9q8I=,iv:ipZrQnYM777JrfuXfcSaCl3PwG0mit4XTaV9SXLRLKE=,tag:0YfmSdjonaJiOqtn30JIKA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:P/pgy07LIL3mgOJx/A/xB+7LSqL9USqOmK4Vd+SDoYq/5wDqmA==,iv:xJwcLQ1uf7urJ2moJUsbVIlwGrdtnZvEv4TV5tYGk/o=,tag:N8wz5Fn3yNYpe5/VbN2I5A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:jLCaL6MP+oGarcMTRg==,iv:4DE6mt4rhd5PYYRvh2PftI7vZMnaURJckUiCPwUYdPA=,tag:pVQr5hKRalacnaennGhe9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13hlaygu79nwrl75zazp9dan7pp0ypx4shyx5f8d7cwaa67xfhgdq04y6r6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTmNycUtTNm9qV29jVTF6
            VGhEV2VXK3FtK1hLeVorc1ZoWG5sQUx1bGxzCkRqT0krSzdrS3VUUGFxL2JIYmx4
            WEN4THhSSVpMMUVXTGhiK3FYRjhZb00KLS0tIC8xWGZZZDMxT0Fndi9LQldNblF3
            ckdDQ2R1NUU3d1lVd1ZjNnhGSDNQTFEKRAOEw/J1AiICaBKTj5CHEAKdHiiFm1ik
            mbDuF4Y68ZchFVmG88vWPpQzsQ6yEkH0VQ80h+7kNdpFQU0d4JyapA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-19T15:25:02Z"
    mac: ENC[AES256_GCM,data:1IbII/0zz3KGyXQ5qQWUiGohEUzt6dTfjcisCZEf0hZQa23ChJRC72aPo/q+AAgTpmsHl77HQptU2sdTdXES/9Yl4G6L62c/uRSJ5wtSBR186KfiePuiKUNxU74z5ffnOJLdnqD6ZYgFre7X/7Dw4ny/7QbDTtuwZNXJvXGjYZc=,iv:jXrEp9UXiyb405XejTzBu4Xrk0NQsVQGmfZYPV9/agE=,tag:j5q15CMg1sasif/91lOUvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
