---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Asia/Dubai
  METALLB_LB_RANGE: 192.168.1.70-192.168.1.80
  METALLB_K8S_GATEWAY_ADDR: 192.168.1.70
  METALLB_TRAEFIK_ADDR: 192.168.1.71
