---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/k8s-at-home/sonarr-develop
      tag: v3.0.8.1537
      pullPolicy: IfNotPresent
    env:
      TZ: Asia/Dubai
      PUSHOVER_DEBUG: "false"
      PUSHOVER_APP_URL: &host "{{ .Release.Name }}.${SECRET_PUBLIC_DOMAIN}"
    envFrom:
      - secretRef:
          name: *app
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          # hajimari.io/enable: "true"
          # hajimari.io/icon: "weather-sunset"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
        hosts:
          - host: "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sonarr.${SECRET_DOMAIN}"
            secretName: "sonarr-tls"
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v1
      # media:
      #   enabled: true
      #   type: nfs
      #   server: "expanse.${SECRET_PRIVATE_DOMAIN}"
      #   path: /tycho/Media
      #   mountPath: /media
      # backup:
      #   enabled: true
      #   type: nfs
      #   server: "expanse.${SECRET_PRIVATE_DOMAIN}"
      #   path: /tycho/Apps/External/Backups/sonarr
      #   mountPath: /config/Backups
      #   readOnly: false
      # scripts:
      #   enabled: true
      #   type: configMap
      #   name: sonarr-pushover
      #   subPath: notify.sh
      #   mountPath: /scripts/pushover-notify.sh
      #   defaultMode: 0775
      #   readOnly: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: sonarr-pushover
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 1000Mi
