---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-config-v1
  namespace: hopme
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
